### ISSUE TITLE
BGFX Attrib Enum incorrect.

### ISSUE THREAD

**Issue by mikaib** [dazKind/linc_bgfx#1]
The generated enum:
![afbeelding](https://github.com/dazKind/linc_bgfx/assets/70071615/cbe7b942-c7ef-4c35-98e1-42654fc3721c)

Expected enum:
![afbeelding](https://github.com/dazKind/linc_bgfx/assets/70071615/b9da5004-f098-456d-bfd4-39406e3dfd3d)

It seems like the enum is being generated incorrectly.
I have not verified if this is the case with other enums, so far this is the only enum with problems that I've found.
If I see other broken enums I'll report that here.

With kind regards,
http80

**Comment by dazKind** [comment]
fixed in f462532f7bfbffdf6d9e7817d6cc5c690ebc1f02
