### ISSUE TITLE
setViewName missing string length

### ISSUE THREAD

**Issue by mikaib** [dazKind/linc_bgfx#2]
The function requires 3 parameters in BGFX:
``setViewName(viewId, name, length) with types (ViewId, const char *, int32_t)``

The externs don't give the string length to the function.

Expected:
![afbeelding](https://github.com/dazKind/linc_bgfx/assets/70071615/d15e07ce-d72e-4dc2-9914-edff7012b9e4)

Actual output:
![afbeelding](https://github.com/dazKind/linc_bgfx/assets/70071615/11bd21ed-42c7-4447-acd1-97bdd1486894)

This causes the build to fail.
I have not checked if there are other functions with the same problem.

**Comment by dazKind** [comment]
fixed in f462532f7bfbffdf6d9e7817d6cc5c690ebc1f02
